### ISSUE TITLE
[Bug Report] `i` Keybinding not Documented

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#12]
In the latest version v0.1.1, the command `i` for editing the selected journal when the buffer is focused is not documented.

**Comment by AmmarAbouZor** [comment]
Actually you can use vim keybindigs to enter insert mode while the textbox is focused and not in edit(insert) mode. But I didn't mention them explicitly because they are normal vim keybindings.
 
The keys that already implemented are: i, I, a, A, o, O

I think I it would be better to add a small paragraph to that vim motions are used in editor in normal mode and Emacs are used in edit mode to the help popup.
I want to make some adjustment on the popup help anyway since commands with many keybindigs appears more than once. I'll add the small paragraph to it as well. Thanks for pointing it out
