### ISSUE TITLE
Unknown query parameter

### ISSUE THREAD

**Issue by rfpozo** [AmmarAbouZor/tui-journal#131]
Error: error with configuration: unknown query parameter `\C:\Users\asus\Documents\tui-journal\entries.db` while parsing connection URL

Caused by:
    unknown query parameter `\C:\Users\asus\Documents\tui-journal\entries.db` while parsing connection URL

Im running windows 11 and I installed the app via cargo command

**Comment by AmmarAbouZor** [comment]
I think this problem came from path handling differences between Windows and Unix-based OS. I'll setup a windows VM and look into it.

In the meantime you still can use the app with the json back-end and when this issues is fixed, you can always export your journals from the json and import them to the sqlite file.
