### ISSUE TITLE
windows always repeat typing

### ISSUE THREAD

**Issue by itbaby** [AmmarAbouZor/tui-journal#266]
when you type one char , the same two char will be typing. 
powershell , window 10 +11
![image](https://github.com/AmmarAbouZor/tui-journal/assets/4564952/95a2aca3-785a-4656-89ac-d2a2de6fa097)
please help to check

**Comment by AmmarAbouZor** [comment]
This looks like a problem with the input text box on windows... I'll need more infos to get closer to the problem

- Does this problem appear in different input fields in the same app, like the tags input box or the built-in Editor?
- Which Version of the app are you currently using?
- Have you compiled it on your machine or did you use the pre-compiled binary from the release page?

Unfortunately I don't have access to a windows machine currently so I can't reproduce it locally, but we can narrow it down and see where the problem lies

**Comment by itbaby** [comment]
Hi AmmarAbouZor ,

- Does this problem appear in different input fields in the same app, like the tags input box or the built-in Editor?
Yes, it always repeating in all tags , it seems that the TUI framework issues ? may be 

- Which Version of the app are you currently using?
I used last 3 versions. it doesn't works 

- Have you compiled it on your machine or did you use the pre-compiled binary from the release page?
I used the pre-comiled version. 

meanwhile thanks so much your feedback.

**Comment by AmmarAbouZor** [comment]
I've tested it on windows machine. It seems to be a problem with `crossterm` crate and how they accept the input stream on windows. I'll try to setup a windows development environment in the next few days to check where the problem lies

**Comment by AmmarAbouZor** [comment]
I've found the problem. It's that crossterm now emitting to key events on windows one for press and the other for release. A fix and release is coming right away

**Comment by AmmarAbouZor** [comment]
A new release with a fix for this problem is out. @itbaby Please check it and let me know if this release didn't fix the problem on your machine

**Comment by itbaby** [comment]
Hi  @AmmarAbouZor it works. thanks for you do the changes.
