### ISSUE TITLE
the shortcut in windows terminal still not got triggered susscessfully. 

### ISSUE THREAD

**Issue by itbaby** [AmmarAbouZor/tui-journal#319]
I am on windows, with windows terminal. when try to typing ? get help. there is no popup show .

![image](https://github.com/AmmarAbouZor/tui-journal/assets/4564952/0a8fb559-0793-412a-8e6a-c0399bf6921d)

**Comment by AmmarAbouZor** [comment]
I've tried that in all available versions of the program and it didn't work in any of them. Very odd!

I think it's something in the Unicodes in windows that is different from Unix systems. My first try will be to change the short cut on windows to see if the problem is from the shortcut or from the program itself
