### ISSUE TITLE
Cargo Install v0.8.2 is not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by rodrigovb96** [AmmarAbouZor/tui-journal#375]
The title says it all, I can't install the app in ubuntu 22.04, I've tried the default command and the ones with only json or sql.

The compilation fails and complains about ratatui version, I noticed that main branch has a newer version than v0.8.2, so I've built it manually and it worked :) 

Maybe releasing a v0.8.3 would fix this issue.

Edit: Ran ```cargo install --path $(pwd)``` in the root folder, after build, and it worked.

**Comment by AmmarAbouZor** [comment]
I think it would be better to release a new version for all the newer dependencies. I'll be working on that...
But I think the current installation should work if you use the flag `--locked` because it will take the dependencies from the file `cargo.lock`.

I think it would be better to update the install command in the README and make 
```bash 
cargo install tui-journal --locked
``` 
I'll update the README and make a new release with the updated dependencies soon
