### ISSUE TITLE
Support undoing actions

### ISSUE THREAD

**Issue by orhun** [AmmarAbouZor/tui-journal#404]
I sometimes edit or delete something in `tui-journal` then I immediately change my mind. It would be nice to store the action in memory (until restart) and support undoing it 🐻 

From the code standpoint I don't have a design for this in my mind but happy to discuss it further if you think it is appropriate!

**Comment by AmmarAbouZor** [comment]
Thanks for the suggestion it looks interesting to implement such a feature and investigate how other apps have implement their undo trees.

The basic implementation in my head is to save the undo stack in a temporary file while the program is running, and we need to define the a serializable actions like add, delete, update... with their meta-data. This can implemented inside the `App` struct and it can save each call to its methods, but I still need to make farther investigation to see how others have implement this too, because maybe we can find more sophisticated solution.

I'll try to start with it as soon as get some time for this project, but maybe it will be a while (A month, or so) until I get to it

**Comment by orhun** [comment]
That sounds good! I am 99% sure I came across a crate that might help with saving stuff to disk & de/serialization but I can't remember its name :/
