### ISSUE TITLE
Can't copy/paste with the mouse

### ISSUE THREAD

**Issue by dupgit** [AmmarAbouZor/tui-journal#422]
Hi,

I'm an happy Linux user an therefor very used to use the mouse to copy/paste things around. Is it possible to support copy/paste with the mouse in any part of tui-journal ?

Thanks.

**Comment by AmmarAbouZor** [comment]
Hi, 

Thanks for your suggestion it would be helpful for sure to have some mouse support, however the app in the current states doesn't have support for mouse at all, since it was thought to be a simple app. You still can use an external terminal editor that supports copying with the mouse.

I'll add the general mouse support to the app road map, after that it would be possible to add support to copy/paste if the underlying editor has support for it :thu

**Comment by dupgit** [comment]
Hi, my editor is vim and it handles nicely copying and pasting with the mouse but when invoked in tjournal I can not select (copy) nor paste anything with the mouse. When going in insertion mode, if i move the mouse vim switches back to normal mode. Is it possible that tjournal is grabbing the mouse and sends that to the "screen" where the editor has been invoked ?
