### ISSUE TITLE
where should I place the config.toml?

### ISSUE THREAD

**Issue by ixzh** [AmmarAbouZor/tui-journal#475]
I created `mkdir ~/.config/tui-journal` and put `config.toml` there. Seems it's not working.

**Comment by AmmarAbouZor** [comment]
You can let the app itself write the configuration file for you then you can start editing it:
* At first remove the directory you created with its content
* Then start the program with flag `tjournal -w` which will write the current configuration to the config file creating all the needed directories.
* After that you can close the program and then search your system for the directory `tui-journal` with the file `config.toml` within, which should have the default configurations written.

Please let me know if this solved the issue on your device, otherwise I would need more information (Your operating system, config file...)

**Comment by ixzh** [comment]
I'm on macOS and starting `tjournal -w` created a folder `Library/Application Support/tui-journal/`. I can work thereon.  Thanks!
