### ISSUE TITLE
[ feature request ] Use XDG paths

### ISSUE THREAD

**Issue by yonas** [AmmarAbouZor/tui-journal#504]
Allows the user to set a universal override path for config and data.

Defaults to ~/.config for settings and ~/.local/share for data.

## Resources
- [xdg crate](https://docs.rs/xdg/latest/xdg/struct.BaseDirectories.html)
- [XDG spec](https://specifications.freedesktop.org/basedir-spec/latest)

**Comment by AmmarAbouZor** [comment]
Thanks for the request I think it make sense to make all the paths configurable via CLI arguments... 
I still need some information  to know exactly what do we need to do:

## Config path:
The app currently saves to configuration on Linux in `~/.config/tui-journal` which is the expected behavior. However I can't tell if the configuration path match XDG spec on other operating system. Could you please let me know if the behavior on your operating system doesn't match the XDG specs

## Data Path
We save different kind of data to different places. 
* The journals (on both backends) are saved into `Document` Directory on each platform since this data, and they can be set from command line arguments as well.  
*  The app's state is saved into the data directory on Linux `~/.local/share/tui-journal`, but again I can't confirm that it behaves as expected on other platforms as well.
So could you tell me please which data are we talking about here and how it behave on your operating system

**Comment by yonas** [comment]
:heavy_check_mark: **Config**: saves to `~/.config/tui-journal`
:x: **Data**: on FreeBSD, it saves documents to `~/tui-journal/entries.db`
:x: **App state**: should be saved in `~/.local/state` instead of `/.local/share`

**Comment by AmmarAbouZor** [comment]
Thanks for the answers... I'll start working on a solution to improve the defaults without introducing major breaking changes and to make the default path configurable

**Comment by AmmarAbouZor** [comment]
@yonas I've implemented fixes and changes without introducing breaking changes on the users. The changes are already in master but I won't create any release until I get to test them on Windows machine (Next Tuesday maybe).

Please feel free to test the changes and reopen this issue or a new one if something still doesn't work as intended on FreeBSD
