### ISSUE TITLE
[Feature Request] Export Option for Active Journal

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#6]
Thank you for this application, it is very useful to take notes on active projects!

I would like to ask you to add an export option for the currently selected journal such that the entered text can be backed up in a different file as well as be processed by other tools.  The entire buffer might be dumped into a plain text file named according to the user's input.  One use case might be that a journal is valid source code which should be compiled, e.g. the journal could be written in Markdown and shall be turned into a PDF by Pandoc.

**Comment by AmmarAbouZor** [comment]
Hi,
thanks for the suggestion. I think an export function could be very useful in many use-cases and I want to take this idea furthermore to add a functionality for multi-selection from journals and then export them as a json array but this would be in a different feature.

For now I would add the a simple export for the content of the selected journey, with following work flow:
1- While journeys list is focused the users triggers the export with a key (maybe '>' since 'e' is already taken)
2- A pop-up view shows with a text box allowing the user to set the path of the file with live validation
3- Export then will happen with a confirmation pop-up

For that I would add some configurations:
- Default export path
- An option to use the current directory as path
- An option to suppress the confirmation pop-up
