### ISSUE TITLE
[Suggestion] Automatic Version Increment and CFF Self-maintenance

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#68]
Aeruginous v2.2.0 has two new and interesting features:  a version incrementing system as well as a CFF release date updater.  As we assemble the RONLOG with Aeruginous, anyway, I would like to suggest to also add the version incrementing feature and the CFF release date synchronisation to the RONLOG assembly workflow because I noticed that these aspects became out of sync, somehow.

Your benefit would be that would only need to activate the RONLOG assembly workflow and all hard-coded version numbers in the entire code base would be updated automatically.

**Comment by AmmarAbouZor** [comment]
Thanks for the helpful suggestion @kevinmatthes
Currently, I still prefer to manage the releases manually, since the app is changing rapidly and there are some features that related for each other (Like tags and filter, then filter and filter popup). That's why I think controlling the versioning manually could be better for the current development phase.

For that I have two suggestions:
1. We Add CFF release date synchronization without the auto-incrementing feature for version if that's possible.
2. We can implement both feature but we make their workflow starts manually if find this approach better to implement.

I'll be glade to hear your opinion about that

**Comment by AmmarAbouZor** [comment]
Thanks for the detail explanations!

I think it would be very useful to include the version incrementing feature within the workflow that assembles the CHANGELOG, since this workflow will be called before each release. 
Doing that would make creating a new release just a breeze with triggering the workflow with the wanted arguments, then creating a new tag which will launch the release workflow :100:  

If you think that including the CFF release date in the same workflow would be better then you can include it there too :+1:
