### ISSUE TITLE
Build In Release Pipeline doesn't work

### ISSUE THREAD

**Issue by AmmarAbouZor** [AmmarAbouZor/tui-journal#84]
I the last release I tried the build binaries for it but it failed with different error messages. 
This workflow should be rewritten with make file which can be tested separately

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

The workflow step is defined to apply a matrix with two input sets, $T$ for the target binaries and $O$ for the operating systems to compile them on.  The resulting workflow job will run for each element of the set $T \times O$ meaning the attempt to compile every target binary on every platform, implying 12 theoretical binaries to attach.  The problem is that each platform does not necessarily allow for cross-compilation to any other one causing the build to fail.

My suggestion is to rewrite the asset generation job to four different jobs which all depend on the successful creation of the GitHub release such that they can run in parallel.  The four jobs should only differ in the runner's OS and the asset's name.  To reduce repetitive code, we can refactor those four jobs in a second step.  Separating the logic into four different jobs shall make sure that we have a working base setup we can build on later on.

**Comment by AmmarAbouZor** [comment]
@kevinmatthes 
Thanks for the suggestion. I'm intending to rewrite the whole creating binary section from scratch using MakeFiles since it's easier to test and we can use it in the development as well. I hope to get into that in the next days
